// Configuration des champs pour le formulaire client avec Formik
export const CLIENT_FORM_CONFIG = {
  groups: [
    {
      title: "📋 Informations principales",
      fields: [
        {
          name: "code",
          label: "Code client",
          type: "text",
          required: true,
          placeholder: "Ex: CLI001",
        },
        {
          name: "rsoc",
          label: "Raison sociale",
          type: "text",
          required: true,
          placeholder: "Nom de l'entreprise",
        },
        {
          name: "mf",
          label: "Matricule fiscal",
          type: "text",
          placeholder: "Matricule fiscal",
        },
        {
          name: "RC",
          label: "RC (Registre de commerce)",
          type: "text",
          placeholder: "Numéro RC",
        },
      ],
    },
    {
      title: "📍 Adresse et coordonnées",
      fields: [
        {
          name: "adresse",
          label: "Adresse",
          type: "textarea",
          rows: 2,
          placeholder: "Adresse complète",
        },
        {
          name: "ville",
          label: "Ville",
          type: "text",
          placeholder: "Ville",
        },
        {
          name: "CP",
          label: "Code postal",
          type: "text",
          placeholder: "Code postal",
        },
        {
          name: "cville",
          label: "Code ville",
          type: "text",
          placeholder: "Code ville",
        },
        {
          name: "tel",
          label: "Téléphone principal",
          type: "tel",
          placeholder: "+216 XX XXX XXX",
        },
        {
          name: "tel2",
          label: "Téléphone secondaire",
          type: "text",
          placeholder: "+216 XX XXX XXX",
        },
        {
          name: "fax",
          label: "Fax",
          type: "tel",
          placeholder: "Numéro de fax",
        },
        {
          name: "email",
          label: "Email principal",
          type: "email",
          placeholder: "email@exemple.com",
        },
      ],
    },
    {
      title: "👥 Contacts entreprise",
      fields: [
        {
          name: "percon1",
          label: "Contact 1",
          type: "text",
          placeholder: "Nom du contact principal",
        },
        {
          name: "respercon1",
          label: "Responsable contact 1",
          type: "text",
          placeholder: "Responsabilité du contact",
        },
        {
          name: "telpercon1",
          label: "Téléphone contact 1",
          type: "tel",
          placeholder: "+216 XX XXX XXX",
        },
        {
          name: "emailpercon1",
          label: "Email contact 1",
          type: "email",
          placeholder: "contact1@exemple.com",
        },
        {
          name: "percon2",
          label: "Contact 2",
          type: "text",
          placeholder: "Nom du contact secondaire",
        },
        {
          name: "respercon2",
          label: "Responsable contact 2",
          type: "text",
          placeholder: "Responsabilité du contact",
        },
        {
          name: "telpercon2",
          label: "Téléphone contact 2",
          type: "tel",
          placeholder: "+216 XX XXX XXX",
        },
        {
          name: "emailpercon2",
          label: "Email contact 2",
          type: "email",
          placeholder: "contact2@exemple.com",
        },
        {
          name: "percon3",
          label: "Contact 3",
          type: "text",
          placeholder: "Nom du contact tertiaire",
        },
        {
          name: "respercon3",
          label: "Responsable contact 3",
          type: "text",
          placeholder: "Responsabilité du contact",
        },
        {
          name: "telpercon3",
          label: "Téléphone contact 3",
          type: "tel",
          placeholder: "+216 XX XXX XXX",
        },
        {
          name: "emailpercon3",
          label: "Email contact 3",
          type: "email",
          placeholder: "contact3@exemple.com",
        },
      ],
    },
    {
      title: "💰 Informations financières",
      fields: [
        {
          name: "soldeinit",
          label: "Solde initial",
          type: "number",
          placeholder: "0.00",
          step: "0.01",
        },
        {
          name: "prix",
          label: "Catégorie de prix",
          type: "text",
          placeholder: "Catégorie tarifaire",
        },
        {
          name: "mtreg",
          label: "Montant règlement",
          type: "number",
          placeholder: "0.00",
          step: "0.01",
        },
        {
          name: "remise",
          label: "Remise (%)",
          type: "number",
          placeholder: "0",
          min: "0",
          max: "100",
          step: "0.1",
        },
        {
          name: "scredit",
          label: "Solde crédit",
          type: "number",
          placeholder: "0.00",
          step: "0.01",
        },
        {
          name: "srisque",
          label: "Solde risque",
          type: "number",
          placeholder: "0.00",
          step: "0.01",
        },
        {
          name: "delaireg",
          label: "Délai règlement (jours)",
          type: "number",
          placeholder: "30",
          min: "0",
        },
        {
          name: "tauxret",
          label: "Taux retenue (%)",
          type: "number",
          placeholder: "0",
          min: "0",
          max: "100",
          step: "0.1",
        },
      ],
    },
    {
      title: "🏦 Informations bancaires",
      fields: [
        {
          name: "banque",
          label: "Banque",
          type: "text",
          placeholder: "Nom de la banque",
        },
        {
          name: "RIB",
          label: "RIB",
          type: "text",
          placeholder: "Relevé d'identité bancaire",
        },
        {
          name: "codebanq",
          label: "Code banque",
          type: "text",
          placeholder: "Code banque",
        },
        {
          name: "adressebanque",
          label: "Adresse banque",
          type: "textarea",
          rows: 2,
          placeholder: "Adresse complète de la banque",
        },
        {
          name: "numcompte",
          label: "Numéro compte",
          type: "text",
          placeholder: "Numéro de compte",
        },
      ],
    },
    {
      title: "📧 Adresses de facturation",
      fields: [
        {
          name: "adressefact",
          label: "Adresse de facturation",
          type: "textarea",
          rows: 2,
          placeholder: "Adresse pour la facturation (si différente)",
        },
        {
          name: "adressear",
          label: "Adresse AR",
          type: "textarea",
          rows: 2,
          placeholder: "Adresse accusé de réception",
        },
      ],
    },
    {
      title: "🏷️ Classifications",
      fields: [
        {
          name: "codetarif",
          label: "Code tarif",
          type: "text",
          placeholder: "Code tarification",
        },
        {
          name: "libtarif",
          label: "Libellé tarif",
          type: "text",
          placeholder: "Description du tarif",
        },
        {
          name: "codesect",
          label: "Code secteur",
          type: "text",
          placeholder: "Code secteur d'activité",
        },
        {
          name: "libsect",
          label: "Libellé secteur",
          type: "text",
          placeholder: "Description du secteur",
        },
        {
          name: "codereg",
          label: "Code région",
          type: "text",
          placeholder: "Code région géographique",
        },
        {
          name: "libreg",
          label: "Libellé région",
          type: "text",
          placeholder: "Description de la région",
        },
        {
          name: "codeact",
          label: "Code activité",
          type: "text",
          placeholder: "Code d'activité",
        },
        {
          name: "libact",
          label: "Libellé activité",
          type: "text",
          placeholder: "Description de l'activité",
        },
        {
          name: "codetypreg",
          label: "Code type règlement",
          type: "text",
          placeholder: "Code type de règlement",
        },
        {
          name: "libtypreg",
          label: "Libellé type règlement",
          type: "text",
          placeholder: "Description du type de règlement",
        },
        {
          name: "codegr",
          label: "Code groupe",
          type: "text",
          placeholder: "Code groupe client",
        },
        {
          name: "libgr",
          label: "Libellé groupe",
          type: "text",
          placeholder: "Description du groupe",
        },
        {
          name: "codequal",
          label: "Code qualité",
          type: "text",
          placeholder: "Code qualité client",
        },
        {
          name: "libqual",
          label: "Libellé qualité",
          type: "text",
          placeholder: "Description de la qualité",
        },
      ],
    },
    {
      title: "📅 Dates importantes",
      fields: [
        {
          name: "datedebut",
          label: "Date début",
          type: "date",
        },
        {
          name: "datefin",
          label: "Date fin",
          type: "date",
        },
        {
          name: "datecreation",
          label: "Date création",
          type: "date",
        },
        {
          name: "datevalidation",
          label: "Date validation",
          type: "date",
        },
      ],
    },
    {
      title: "⚙️ Paramètres et options",
      fields: [
        {
          name: "regime",
          label: "Régime fiscal",
          type: "select",
          options: [
            { value: "R", label: "Réel" },
            { value: "N", label: "Normal" },
          ],
        },
        {
          name: "rap",
          label: "RAP (Retenue à la source)",
          type: "select",
          options: [
            { value: "N", label: "Non" },
            { value: "O", label: "Oui" },
          ],
        },
        {
          name: "timbre",
          label: "Timbre fiscal",
          type: "checkbox",
        },
        {
          name: "exo",
          label: "Exonération TVA",
          type: "checkbox",
        },
        {
          name: "susp",
          label: "Suspension",
          type: "checkbox",
        },
        {
          name: "reel",
          label: "Client réel",
          type: "checkbox",
        },
        {
          name: "export",
          label: "Client export",
          type: "checkbox",
        },
        {
          name: "validation",
          label: "Statut validation",
          type: "select",
          options: [
            { value: "0", label: "En attente" },
            { value: "1", label: "Validé" },
            { value: "2", label: "Refusé" },
          ],
        },
        {
          name: "blocage",
          label: "Statut blocage",
          type: "select",
          options: [
            { value: "0", label: "Aucun" },
            { value: "1", label: "Bloqué" },
            { value: "2", label: "Suspendu" },
          ],
        },
        {
          name: "parunite",
          label: "Tarification par unité",
          type: "select",
          options: [
            { value: "0", label: "Non" },
            { value: "1", label: "Oui" },
            { value: "2", label: "Mixte" },
          ],
        },
        {
          name: "prod",
          label: "Client producteur",
          type: "checkbox",
        },
      ],
    },
    {
      title: "📝 Informations supplémentaires",
      fields: [
        {
          name: "decision",
          label: "Décision",
          type: "text",
          placeholder: "Décision concernant le client",
        },
        {
          name: "libpost",
          label: "Poste",
          type: "text",
          placeholder: "Poste/Position",
        },
        {
          name: "comptec",
          label: "Compte client",
          type: "text",
          placeholder: "Numéro compte comptable",
        },
        {
          name: "rsocar",
          label: "RS AR",
          type: "text",
          placeholder: "Raison sociale accusé réception",
        },
        {
          name: "message",
          label: "Message/Notes",
          type: "textarea",
          rows: 3,
          placeholder: "Notes ou informations supplémentaires",
        },
        {
          name: "descl",
          label: "Description détaillée",
          type: "textarea",
          rows: 3,
          placeholder: "Description complète du client",
        },
      ],
    },
  ],
};
